[tool.black]
line-length = 120
include = '\.py$'

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
lines_after_imports = 2
use_parentheses = true
ensure_newline_before_comments = true
force_sort_within_sections = true
profile = "black"
